# Generated by Django 5.0.2 on 2024-02-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMovement',
            fields=[
                ('movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('timestamp', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
